name: Deploy static website to Azure Web App - EventTech
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-website
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: static-website

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F4C28DFA7AA346E8A704CCBD7E22CF59 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_236A6A6F380B4C85A266366A13CA9501 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0DD306A2E9574E96A234B922FF6574E9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EventTech'
          slot-name: 'Production'
          package: .

