name: Azure Login

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
      
           client-id:  ${{ secrets.AZUREAPPSERVICE_CLIENTID_F4C28DFA7AA346E8A704CCBD7E22CF59 }}
          tenant-id:  ${{ secrets.AZUREAPPSERVICE_TENANTID_236A6A6F380B4C85A266366A13CA9501 }}
          subscription-id:  ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0DD306A2E9574E96A234B922FF6574E9 }}
             - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EventTech'
          slot-name: 'Production'
          package: .
